const mockInvoices = [
    {
        InvoiceId: "INV-001",
        CustomerName: "Công ty ABC",
        InvoiceDate: "2025-07-01",
        TotalAmount: "5000",
        Currency: "USD",
        Tags: ["Điện", "Tháng 7"],
    },
    {
        InvoiceId: "INV-002",
        CustomerName: "Nguyễn Văn A",
        InvoiceDate: "2025-07-02",
        TotalAmount: "1200",
        Currency: "USD",
        Tags: ["Nước", "Tháng 7"],
    },
    {
        InvoiceId: "INV-003",
        CustomerName: "Công ty XYZ",
        InvoiceDate: "2025-06-28",
        TotalAmount: "2500",
        Currency: "VND",
        Tags: ["Internet"],
    },
    {
        InvoiceId: "INV-004",
        CustomerName: "Trần Thị B",
        InvoiceDate: "2025-07-03",
        TotalAmount: "700",
        Currency: "VND",
        Tags: ["Điện"],
    },
    {
        InvoiceId: "INV-005",
        CustomerName: "Lê Hoàng",
        InvoiceDate: "2025-07-05",
        TotalAmount: "300",
        Currency: "USD",
        Tags: ["Điện thoại", "Cá nhân"],
    },
    {
        InvoiceId: "INV-006",
        CustomerName: "Phạm Công",
        InvoiceDate: "2025-06-30",
        TotalAmount: "1500",
        Currency: "USD",
        Tags: ["Điện", "Văn phòng"],
    },
    {
        InvoiceId: "INV-007",
        CustomerName: "Công ty LMN",
        InvoiceDate: "2025-07-06",
        TotalAmount: "2200",
        Currency: "VND",
        Tags: ["Dịch vụ", "Tháng 7"],
    },
    {
        InvoiceId: "INV-008",
        CustomerName: "Đỗ Minh C",
        InvoiceDate: "2025-07-07",
        TotalAmount: "950",
        Currency: "USD",
        Tags: ["Bảo trì", "Thiết bị"],
    },
    {
        InvoiceId: "INV-009",
        CustomerName: "Công ty OPQ",
        InvoiceDate: "2025-07-08",
        TotalAmount: "6000",
        Currency: "USD",
        Tags: ["Điện", "Sửa chữa"],
    },
    {
        InvoiceId: "INV-010",
        CustomerName: "Nguyễn Văn D",
        InvoiceDate: "2025-07-09",
        TotalAmount: "450",
        Currency: "VND",
        Tags: ["Nước", "Cá nhân"],
    },
];

export default mockInvoices;
